# Generated by Django 4.2.7 on 2024-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_languagephrase_product_delete_languageprase"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagephrase",
            name="text_en",
            field=models.TextField(null=True),
        ),
    ]
