# Generated by Django 4.2.7 on 2024-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_languagephrase_text_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagephrase",
            name="code_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="languagephrase",
            name="code_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="languagephrase",
            name="code_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
