# Generated by Django 4.2.7 on 2024-04-17 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_languagephrase_code_en_languagephrase_code_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languagephrase",
            name="code_en",
        ),
        migrations.RemoveField(
            model_name="languagephrase",
            name="text_en",
        ),
    ]
