# Generated by Django 4.2.7 on 2024-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_languagephrase_code_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
