# Generated by Django 4.2.7 on 2024-04-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_order_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.card",
            ),
            preserve_default=False,
        ),
    ]
